config/routes.rb
NuEraFitness::Application.routes.draw do
  root :to => "content#home"

  match '/cart/quote', :to => 'orders#quote', :via => :post, :as => :quote_cart
	match '/cart/coupon', :to => 'orders#coupon', :via => :post, :as => :coupon_cart

  namespace :admin do
    resources :suppliers
    resources :videos
    resources :products do
      resource :package, :only => [:edit, :update] do
        delete :remove_variant, :on => :member
      end
    end

    resources :orders do
      member do
        get :send_quote
      end
    end
  end
end

app/views/admin/orders/_billing_overview.html.erb
    <h3>Billing Details</h3>
    <table>
      <tr>
        <td>Customer Details</td>
        <td><%= customer_details @order.bill_address %></td>
      </tr>
      <tr>
        <td>Email:</td>
        <td><%= mail_to @order.email %></td>
      </tr>
      <tr>
        <td>Phone Number:</td>
        <td><%= @order.bill_address.phone %></td>
      </tr>
      <tr>
        <td>Order Date</td>
        <td><%= @order.completed_at %></td>
      </tr>
      <tr>
        <td>IP Address:</td>
        <td></td>
      </tr>
      <tr>
        <td>Payment Method</td>
        <td><%= PaymentMethod.find_with_destroyed(@order.payment.payment_method_id).name %></td>
      </tr>
      <tr>
        <td>Transaction Id</td>
        <td></td>
      </tr>
      <tr>
        <td>Payment Status</td>
        <td><%= @order.payment_state.humanize %></td>
      </tr>
      <tr>
        <td colspan="2">
          <% @order.payment.actions.each do |action| %>
            <%= button_to t(action), fire_admin_order_payment_path(@order, @order.payment, :e => action), :remote => true, :method => :put %>
          <% end %>
        </td>
      </tr>
    </table>

app/views/admin/orders/_line_items_overview.html.erb
    <h3>Line Item Details</h3>
    <table>
    <% @order.line_items.each do |item| %>
      <tr>
        <td>
          <%= item.quantity %> x <%= link_to item.variant.name, admin_product_url(item.variant.product) %>
        </td>
        <td style="text-align:right;">
          <%= number_to_currency(item.quantity * item.price) %><br />
          <span id="price-total-<%= item.id %>"><%= number_to_currency(item.actual_price * item.quantity) unless item.actual_price.blank? %></span>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <span class="sku" style="display:block;"><%= item.variant.sku %></span>
          <span class="actual-price">
            <span id="price-form-<%= item.id %>"<%= " style='display:none;'" unless item.actual_price.blank? %>>
              <%= form_for(@order, :url => admin_order_url(@order), :remote => true, :html => {:method => :put}) do |f| %>
                <%= f.hidden_field :number %>
                <%= f.fields_for :line_items, item do |item_form| %>
                  <%= item_form.label :actual_price, 'Actual Price/Unit' %>
                  <%= item_form.text_field :actual_price, :style => 'width:30%' %>
                <% end %>
                <%= f.submit "Save" %>
              <% end %>
            </span>
            <span id="price-label-<%= item.id %>"<%= " style='display:none;'" if item.actual_price.blank? %>>
              <span style="display:inline-block; width:100px;"><%= "Price/Unit: #{number_to_currency item.actual_price}" %></span>
              <input type="submit" onclick='$("#price-label-<%= item.id %>").hide(); $("#price-form-<%= item.id %>").show();' value="Edit" />
            </span>
          </span>
        </td>
    <% end %>
    </table>

app/views/admin/orders/_overview.html.erb
<style>
#order-overview span {
  width: 33.33%;
}
#billing-details, #shipping-details { width:25%; }
#billing-details, #shipping-details { float:left; }
#order-overview table td { border-bottom: 0; }
.order-overview-cell { background-color: #1268D0; color:#FFF;}
.order-overview-cell a { color: #FFF !important; }
#order-overview h3 { text-align: center; background-color: #10B0E6; border-bottom: 3px solid #0000FF; }
#order-details { float:right; }
</style>
<div id="order-overview">
  <span id="billing-details">
    <%= render 'admin/orders/billing_overview' %>
  </span>
  <span id="shipping-details">
    <%= render 'admin/orders/shipping_overview' %>
  </span>
  <span id="order-details">
    <%= render 'admin/orders/line_items_overview' %>
  </span>
</div>

app/views/admin/orders/_shipping_overview.html.erb
    <h3>Shipping Details</h3>
    <table>
      <tr>
        <td>Customer Details</td>
        <td><%= customer_details @order.ship_address %></td>
      </tr>
      <tr>
        <td>Email:</td>
        <td><%= mail_to @order.email %></td>
      </tr>
      <tr>
        <td>Phone Number:</td>
        <td><%= @order.ship_address.phone %></td>
      </tr>
      <tr>
        <td>Shipping Cost</td>
        <td><%= number_to_currency @order.adjustments.shipping.map(&:amount).sum %></td>
      </tr>
      <tr>
        <td colspan="2">
          <h3 style="text-align: left; padding-left: 5px; margin-bottom:-30px;" >Shipments</h3>
          <input style="position:relative; float:right; top:-4px; height:23px;" type="submit" value="Ship All" />
        </td>
      </tr>
      <% @order.shipments.each do |shipment| %>
        <tr>
          <td colspan="2">
            <h4 style="margin:0;"><%= shipment.supplier.name %> (<%= shipment.shipping_method.name %>) <%= number_to_currency shipment.adjustment.amount %></h4>
            <span class="shipment-actions" style="display:block; margin-bottom:8px; width:100%">
              <!-- <input type="submit" value="invoice" /> -->
              <span id="ship-<%= shipment.number %>">
                <% if shipment.can_ship? %>
                  <%= form_tag fire_admin_order_shipment_path(@order, shipment, :e => 'ship'), :remote => true, :method => :put, :confirm => t('are_you_sure') do |f| %>
                    <%= submit_tag 'Ship' %>
                  <% end %>
                <% elsif shipment.shipped? %>
                  Shipped!
                <% else %>
                  Pending
                <% end %>
              </span>
            </span>
            <span class="tracking">
              <span id="tracking-form-<%= shipment.number %>"<%= " style='display:none;'" unless shipment.tracking.blank? %>>
                <%= form_for(shipment, :url => admin_order_shipment_url(@order, shipment), :remote => true, :html => {:method => :put}) do |ship_form| %>
                  <%= ship_form.label :tracking, t(:tracking) + '# :', :style => "display:inline-block; width:30%;" %>
                  <%= ship_form.text_field :tracking, :style => 'width:40%;' %>
                  <%= ship_form.submit 'Save' %>
                <% end %>
              </span>
              <span id="tracking-label-<%= shipment.number %>"<%= " style='display:none;'" if shipment.tracking.blank? %>>
                <span style="display:inline-block; width:70%;"><%= "Tracking #: #{shipment.tracking}" %></span>
                <input type="submit" onclick='$("#tracking-label-<%= shipment.number %>").hide(); $("#tracking-form-<%= shipment.number %>").show();' value="Edit" />
              </span>
            </span>
            <span class="actual-amount">
              <span id="amount-form-<%= shipment.number %>"<%= " style='display:none;'" unless shipment.adjustment.actual_amount.blank? %>>
                <%= form_for(shipment.adjustment, :url => admin_order_adjustment_url(@order, shipment.adjustment), :remote => true, :html => {:method => :put}) do |adjust_form| %>
                  <%= adjust_form.label :actual_amount, 'Cost: ', :style => "display:inline-block; width:30%;" %>
                  <%= adjust_form.text_field :actual_amount, :style => 'width:40%' %>
                  <%= adjust_form.submit 'Save' %>
                <% end %>
              </span>
              <span id="amount-label-<%= shipment.number %>"<%= " style='display:none;'" if shipment.adjustment.actual_amount.blank? %>>
                <span style="display:inline-block; width:70%;"><%= "Cost: #{number_to_currency shipment.adjustment.actual_amount}" %></span>
                <input type="submit" onclick='$("#amount-label-<%= shipment.number %>").hide(); $("#amount-form-<%= shipment.number %>").show();' value="Edit" />
              </span>
            </span>
          </td>
        </tr>
      <% end %>
    </table>

app/views/admin/orders/index.html.erb
<div class='toolbar order-links'>
  <%= button_link_to t("new_order"), new_admin_order_url, :icon => 'add' %>
</div>

<%= render :partial => 'admin/shared/order_sub_menu' %>

<% if Order.quotes.any? %>
<h1><%= t("listing_quotes") %></h1>

<table class="index">
  <thead>
    <tr>
      <th width="15px"></th>
      <th><%= t("order_number") %></th>
      <th><%= t("customer") %></th>
      <th><%= t("total") %></th>
    </tr>
  </thead>
  <tbody>
    <% Order.quotes.each do |quote| %>
      <tr>
        <td><%= link_to '+', admin_order_adjustments_url(quote), :class => 'expand-adjustments', :id => quote.number %></td>
        <td><%= link_to quote.number, object_url(quote) %></td>
        <td><%= quote.name %></td>
        <td><%= number_to_currency quote.total %></td>
      </tr>
      <tr style="display:none;">
        <td colspan="4" id=<%= "adjustments-#{quote.number}" %>>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
  $('.expand-adjustments, .expand-orders').click(function(quote) {
    $.getScript(this.href);
    return false;
  })
})
</script>

<h1><%= t("listing_orders") %></h1>

<table class="index">
  <thead>
    <tr>
      <%= hook :admin_orders_index_headers do %>
        <th width="15px"></th>
        <th><%= order @search, :by => :updated_at,       :as => t("updated_at") %></th>
        <th><%= order @search, :by => :completed_at,     :as => t("order_date") %></th>
        <th><%= order @search, :by => :number,           :as => t("order_number") %></th>
        <th><%= t(:status) %></th>
        <th><%= order @search, :by => :email,            :as => t("customer") %></th>
        <th><%= order @search, :by => :total,            :as => t("total") %></th>
      <% end %>
      <th>
        <%= hook :admin_orders_index_header_actions %>
      </th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <%- locals = {:order => order} %>
      <%= hook :admin_orders_index_rows, locals do %>
        <td><%= link_to '+', admin_order_url(order), :class => 'expand-orders' %></td>
        <td><%= "#{time_ago_in_words(order.updated_at)} ago" %></td>
        <td><%= order.completed_at.to_date if order.completed_at %></td>
        <td><%= link_to order.number, object_url(order) %></td>
        <td><%= order_status(order) %></td>
        <td><%= order.name %></td>
        <td><%= number_to_currency order.total %></td>
      <% end %>
      <td>
        <%= hook :admin_orders_index_row_actions, locals do %>
          <%= link_to_edit order %>
        <% end %>
      </td>
    </tr>
    <tr style="display:none;">
      <td style="padding:0px"; colspan="8" id="expand-order-<%= order.number %>" class="order-overview-cell"></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate(@orders, :previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;") %>


<% content_for :sidebar do %>
<div class="box">
  <h3><%= t(:search) %></h3>

  <%= form_for @search do |f| %>
    <%- locals = {:f => f} %>
    <%= hook :admin_orders_index_search, locals do %>
      <label><%= t("date_range") %></label><br />
      <div class="yui-g date-range-filter">
        <div class="yui-u sub-field first">
          <%= f.spree_date_picker :completed_at_greater_than %><br />
          <label class="sub"><%= t("start") %></label>
        </div>
        <div class="yui-u sub-field">
          <%= f.spree_date_picker :completed_at_less_than %><br />
          <label><%= t("stop") %></label>
        </div>
      </div>

      <p><label><%= t("status") %></label><br />
      <%= f.select :state_equals, Order.state_machines[:state].states.collect {|s| [t("order_state.#{s.name}"), s.value]}, {:include_blank => true} %></p>

      <p><label><%= t 'order_number' %></label><br />
      <%= f.text_field :number_like, :size=>25 %></p>

      <p>
        <label><%= t 'email' %></label><br />
        <%= f.text_field :email_like, :size=>25 %>
      </p>
      <p>
      <label><%= t 'first_name_begins_with' %></label><br />
          <%= f.text_field :bill_address_firstname_begins_with, :size=>25 %>
      </p>
      <p>
        <label><%= t 'last_name_begins_with' %></label><br />
        <%= f.text_field :bill_address_lastname_begins_with, :size=>25 %>
      </p>
      <p>
        <%= f.check_box :completed_at_not_null, {:style => "vertical-align:middle;"} %>
        <label>
          <%= t("show_only_complete_orders") %>
        </label>
      </p>
    <% end %>
    <%= hook :admin_orders_index_search_buttons, locals do %>
      <p><%= button t("search") %></p>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/admin/orders/show.js.erb
$("#expand-order-<%= @order.number %>").html("<%= escape_javascript(render("admin/orders/overview")) %>").parents().show();