config/routes.rb
NuEraFitness::Application.routes.draw do
  root :to => "content#home"

  match '/cart/quote', :to => 'orders#quote', :via => :post, :as => :quote_cart
	match '/cart/coupon', :to => 'orders#coupon', :via => :post, :as => :coupon_cart

  namespace :admin do
    resources :suppliers
    resources :videos
    resources :products do
      resource :package, :only => [:edit, :update] do
        delete :remove_variant, :on => :member
      end
    end

    resources :orders do
      member do
        get :send_quote
      end
    end
  end
end

app/views/shared/_facebook_sdk.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: '2147548118807', status: true, cookie: true, xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
    document.getElementById('fb-root').appendChild(e);
  })();
</script>

app/views/shared/_google_analytics.html.erb
<% if tracker = Tracker.current %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '<%= tracker.analytics_id %>']);
    _gaq.push(['_trackPageview']);

    <% if flash[:commerce_tracking] %>
      _gaq.push(['_addTrans',
        '<%= @order.number %>',
        '',   // Affiliation
        '<%= @order.total %>',
        '<%= @order.tax_total %>',
        '<%= @order.ship_total %>',
        '<%= @order.bill_address.city %>',
        '<%= @order.bill_address.state ? @order.bill_address.state.name : @order.bill_address.state_name %>',
        '<%= @order.bill_address.country.name %>'
      );
      <% @order.line_items.each do |li| %>
        _gaq.push(['_addItem',
          '<%= @order.number %>',
          '<%= li.variant.sku %>',
          '<%= li.variant.name %>',
          '',   // Category or Variation
          '<%= li.price %>',
          '<%= li.quantity %>'
        );
      <% end %>
      _gaq.push(['_trackTrans'])
    <% end %>


    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
<% end %>

app/views/shared/_head.html.erb
<title><%= title %></title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<%= stylesheet_link_tag 'screen' %>
<%= csrf_meta_tag %>
<%= javascript_include_tag 'jquery-1.4.2.min', 'jquery.validate.min.js', 'rails', 'application', :cache => 'jquery-core' %>
<% unless I18n.locale.to_s[0..1] == 'en' %>
  <%= javascript_include_tag ['localization/messages_', I18n.locale.to_s[0..1], '.js'].join %>
<% end %>
<%= yield :head %>
<%= raw meta_data_tags %>

app/views/shared/_login_bar.html.erb
<% if current_user %>
  <li><%= link_to t('my_account'), account_path %></li>
  <li>|</li>
  <li><%= link_to t('logout'), destroy_user_session_path %></li>
<% else %>
  <li><%= link_to t('log_in'), login_path %></li>
<% end %>

app/views/shared/_nav_bar.html.erb
<script type="text/javascript">
$(document).ready(function() {
	$('img.hover').hover(
	function() {
		var temp = $(this).attr('src');
		$(this).attr('src',$(this).attr('togglesrc'));
		$(this).attr('togglesrc',temp);
	},
	function() {
		var temp = $(this).attr('src');
		$(this).attr('src',$(this).attr('togglesrc'));
		$(this).attr('togglesrc',temp);
	});
});
</script>
<% cache(:social_and_search) do %>
  <%= render 'shared/social_and_search' %>
<% end %>
<ul class="nav-bar">
  <% if current_order && current_order.line_items.any? %>
    <%= render 'shared/store_menu' %>
  <% else %>
    <% cache("store-menu-#{current_user ? 1 : 0}") do %>
      <%= render 'shared/store_menu' %>
    <% end %>
  <% end %>
</ul>

app/views/shared/_order_details_line_item_row.html.erb
  <td width="300"><%= item.variant.product.name %> <%= "(#{variant_options(item.variant)})" unless item.variant.option_values.empty? %></td>
  <td class="price"><%= number_to_currency item.price %></td>
  <td class="qty"><%= item.quantity %></td>
  <td class="total"><span><%= number_to_currency (item.price * item.quantity) %></span></td>
<% if item.variant.is_a_package? %>
</tr>
<tr>
  <td colspan="4">
    <ul class="package-variants">
      <% variants = item.variant.package.variants.group(:id) %>
      <% variant_counts = variants.count %>
      <% variants.each do |variant| %>
        <li><%= variant_counts[variant.id] %> x <%= variant.name %></li>
      <% end %>
    </ul>
  </td>
<% end %>

app/views/shared/_products.html.erb
<%
  paginated_products = @searcher.products if params.key?(:keywords)
  paginated_products ||= products
%>
<% if products.empty? %>
  <%= t(:no_products_found) %>
<% elsif params.key?(:keywords) %>
  <h3><%= t(:search_results, :keywords => h(params[:keywords])) %></h3>
<% end %>
 
<% if products.any? %>
<ul class="product-listing">
  <% products.sort {|a,b| a.name <=> b.name}.each do |product| %>
    <% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
      <li id="product_<%= product.id %>" class="<%= product.has_variants? ? "variants" : "" %>">
        <%= link_to small_image(product), product %>
        <%= link_to raw(product.name + " <span class='price selling'>#{product_price(product)}</span>"), product, :class => 'info' %>
      	<% if product.has_stock? || Spree::Config[:allow_backorders] %>
          <%= form_for :order, :url => populate_orders_url do |f| %>
            <% if product.has_variants? %>
              <%= select_tag "products[#{product.id}]", options_from_collection_for_select(product.variants, :id, :options_text) %>
            <% end %>
            <%= text_field_tag (product.has_variants? ? :quantity : "variants[#{product.master.id}]"), 1, :class => "title", :size => 3 %>
            &nbsp;
            <button type='submit'>
              <%= image_tag('/images/add-to-cart.png') + t('add_to_cart') %>
            </button>
          <% end %>
        <% else %>
          <%= content_tag('strong', t('out_of_stock')) %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>
<% end %>

<% if paginated_products.respond_to?(:total_pages)
      params.delete(:search)
      params.delete(:taxon)
      
%>
<hr class="space" />
<%= will_paginate(paginated_products,
                    :previous_label => "&#171; #{t('previous')}",
                    :next_label => "#{t('next')} &#187;") %>
<hr class="space" />
<% end %>
<div class="clear"></div>

app/views/shared/_products_small.html.erb
<%
  paginated_products = @searcher.products if params.key?(:keywords)
  paginated_products ||= products
%>
<% if products.empty? %>
  <%= t(:no_products_found) %>
<% elsif params.key?(:keywords) %>
  <h3><%= t(:search_results, :keywords => h(params[:keywords])) %></h3>
<% end %>
 
<% if products.any? %>
<ul class="product-listing">
  <% products.each do |product| %>
    <% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
      <li id="product_<%= product.id %>" class="<%= product.has_variants? ? "variants" : "" %>">
        <%= link_to small_image(product, :width => '100') , product  %>
        <%= link_to raw(product.name + " <span class='price selling'>#{product_price(product)}</span>"), product, :class => 'info' %>
      	<% if product.has_stock? || Spree::Config[:allow_backorders] %>
        <% else %>
          <%= content_tag('strong', t('out_of_stock')) %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>
<% end %>

<% if paginated_products.respond_to?(:total_pages)
      params.delete(:search)
      params.delete(:taxon)
      
%>
<hr class="space" />
<%= will_paginate(paginated_products,
                    :previous_label => "&#171; #{t('previous')}",
                    :next_label => "#{t('next')} &#187;") %>
<hr class="space" />
<% end %>
<div class="clear"></div>
<h3><%= link_to "See all " + taxon.name , seo_url(taxon) %></h3>
<div class="clear"></div>

app/views/shared/_quote_details.html.erb
<table class="index">
  <tbody id="line-items">
    <tr>
      <%= hook :quote_details_line_items_headers do %>
        <th><%= t :item_description %></th>
        <th class="price"><%= t :price %></th>
        <th class="qty"><%= t :qty %></th>
        <th class="total"><%= t :total %></th>
      <% end %>
    </tr>
    <% @order.line_items.each do |item| %>
      <tr>
        <% locals = {:item => item} %>
        <%= hook :quote_details_line_items_row, locals do %>
          <td width="300"><%= item.variant.product.name %> <%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %></td>
          <td class="price"><%= number_to_currency item.price %></td>
          <td class="qty"><%= item.quantity %></td>
          <td class="total"><span><%= number_to_currency (item.price * item.quantity) %></span></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
  <%= hook :quote_details_subtotal do %>
    <tbody id="subtotal">
      <tr class="total" id="subtotal-row">
        <td colspan="3"><b><%= t :subtotal %></b></td>
        <td class="total"><span><%= number_to_currency @order.item_total %></span></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/shared/_search.html.erb
<% @taxons = @taxon && @taxon.parent ? @taxon.parent.children : Taxon.roots  %> 
<%= form_tag products_url, :method => :get do %>
  <%= submit_tag '', :name => nil, :class => 'search-submit' %>
  <%= text_field_tag :keywords, params[:keywords] %>
<% end %>

<script type="text/javascript">
	$(document).ready(function() {
		$("#header input#keywords").focus(function() {
			if($(this).val() == 'Find a product') {
				$(this).val('');
				$(this).css('color','#ffffff');
			}
		});
		$("#header input#keywords").blur(function() {
			if($(this).val() == '') {
				$(this).val('Find a product');
				$(this).css('color','#bbbbbb');
			}
		});
		$("#header input#keywords").blur();
	});
</script>

app/views/shared/_social_and_search.html.erb
<ul id="social-and-search">
  <li><%= link_to_facebook %></li>
  <li><%= link_to_twitter %></li>
  <% #<li><a href="" target="_blank"><img class="hover" togglesrc="/images/flickr-over.png" src="/images/flickr-over.png" border="0" /></a></li> %>
  <li><%= render 'shared/search' %></li>
</ul>

app/views/shared/_store_menu.html.erb
<li><%= link_to t("about"), '/about' %></li>
<li>|</li>
<li><%= link_to t("contact"), '/contact_us' %></li>
<li>|</li>
<li><%= link_to t('my_account'), account_path %></li>
<% if current_user %> 
  <li>|</li>
  <li><%= link_to t('logout'), destroy_user_session_path %></li>
<% end %>
<% if current_order && current_order.line_items.any? %>
<li>|</li><li>
<%= link_to_cart %>
</li>
<% end %>

app/views/shared/_subfooter.html.erb
<div id="subfooter"><br />&copy;&nbsp;Nu Era Fitness 2011. All Rights Reserved. | 888-469-3445 | <a href="mailto:questions@nuerafitness.com">questions@nuerafitness.com</a></div>
</div>

app/views/shared/_taxonomies.html.erb
<% cache("taxonomies_sidebar_#{@taxon ? @taxon.id : '0'}") do %>
<div class="rounded-box" style="width:140px;">
<div id="taxonomies" class="sidebar-item">
<% get_taxonomies.each do |taxonomy| %>
  <% next if taxonomy.name == 'Google' %>
  <ul class="navigation-list">
    <li<%= ' class="current"' if @taxon && @taxon == taxonomy.root %>><%= link_to t("shop_by_taxonomy", :taxonomy => taxonomy.name.singularize), seo_url(taxonomy.root), :class => 'root' %></li>
    <% taxonomy.root.children.each do |taxon| %>
      <li<%= ' class="current"' if @taxon and ([@taxon] + @taxon.ancestors).include?(taxon) %>><%= link_to taxon.name, seo_url(taxon) %></li>
    <% end %>
  </ul>
<% end %>
</div>
</div>
<% end %>