config/routes.rb
NuEraFitness::Application.routes.draw do
  root :to => "content#home"

  match '/cart/quote', :to => 'orders#quote', :via => :post, :as => :quote_cart
	match '/cart/coupon', :to => 'orders#coupon', :via => :post, :as => :coupon_cart

  namespace :admin do
    resources :suppliers
    resources :videos
    resources :products do
      resource :package, :only => [:edit, :update] do
        delete :remove_variant, :on => :member
      end
    end

    resources :orders do
      member do
        get :send_quote
      end
    end
  end
end

app/views/products/show.html.erb
<% @body_id = 'product-details' %>
<% if @product.images.any? %>
  <%= facebook_meta(@product.name, 'product', product_url(@product), "http://www.nuerafitness.com#{@product.images.first.attachment.url(:product)}") %>
<% end %>
<h1><%= @product.name %></h1>

<% content_for :sidebar do %>
	<div style="height:37px;">&nbsp;</div>
  <%= hook :taxon_sidebar_navigation do %>
    <%= render :partial => "shared/taxonomies" %>
  <% end %>
<% end %>

<div id="product-images-and-description">
  <div id="product-images">
    <%= hook :product_images do %>
    <div id="main-image">
	  <%= render 'image' %>
    </div>
    <div id="thumbnails">
	  <%= render 'thumbnails', :product => @product %>
    </div>
    <% end %>
  </div>
  
  <%= hook :cart_form do %>
    <div id="cart-form">
      <%= render 'cart_form' %>
    </div>
  <% end %>
  
  <div style="margin-left:10px;">
    <fb:like href="<%= product_url(@product) %>" colorscheme="dark" send="true" show_faces="true" width="450" action="recommend"></fb:like>
  </div>

  <div id="product-description">
    <%= hook :product_description do %>
	  <%= product_description(@product) rescue t("product_has_no_description") %>
    <% end %>
    <%= hook :product_properties do %>
	  <%= render 'properties' %>
    <% end %>
  </div>

</div>



<% #render 'taxons' %>