config/routes.rb
NuEraFitness::Application.routes.draw do
  root :to => "content#home"

  match '/cart/quote', :to => 'orders#quote', :via => :post, :as => :quote_cart
	match '/cart/coupon', :to => 'orders#coupon', :via => :post, :as => :coupon_cart

  namespace :admin do
    resources :suppliers
    resources :videos
    resources :products do
      resource :package, :only => [:edit, :update] do
        delete :remove_variant, :on => :member
      end
    end

    resources :orders do
      member do
        get :send_quote
      end
    end
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
	has_and_belongs_to_many :products
	
	validates_presence_of :name, :description, :url, :publish_up
	
	#def active?
		#self.publish_up > Date.today
	#end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
	
	respond_to :html

  def index
    params[:search] ||= {}
    @search = Video.metasearch(params[:search])
    
    @videos = Video.metasearch(params[:search]).paginate(
                                   :per_page => Spree::Config[:orders_per_page],
                                   :page => params[:page])
		
    respond_with(@videos)
  end
  
  # we don't want a show method
  resource_controller :except => [ :show ]
	
  # redirect to the edit action after create
  create.response do |wants|
    wants.html { redirect_to edit_admin_video_url( @video ) }
  end

  # redirect to the edit action after update
  update.response do |wants|
    wants.html { redirect_to edit_admin_video_url( @video ) }
  end

end

app/views/admin/videos/_form.html.erb
<div class="yui-gc">
<%= f.field_container :name do %>
	<%= f.label :name, t("name")%><br />
	<%= f.text_field :name %>
<% end %>
<%= f.field_container :description do %>
	<%= f.label :description , t("description")%><br />
	<%= f.text_area :description %>
<% end %>
<%= f.field_container :url do %>
	<%= f.label :url , t("youtube_url")%><br />
	<%= f.text_field :url %>
<% end %>
<%= f.field_container :publish_up do %>
	<%= f.label :publish_up , t("publish_up")%><br />
	<%= f.spree_date_picker :publish_up %>
<% end %>
<%= f.field_container :publish_down do %>
	<%= f.label :publish_down , t("publish_down")%><br />
	<%= f.spree_date_picker :publish_down %>
<% end %>
<%= f.label :product_id, t("products") %><br />
<%= grouped_collection_select(:video, :product_ids, Taxon.all, :products, :name, :id, :name, { :selected => @video.product_ids }, { :multiple => true, :size => 10 }) %>

app/views/admin/videos/_sub_menu.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav">
    <% # Default tab helper function always on for video sub-tab so <li> constructed manually below %>
    <li class="<%= ( params[:action] == "index" ) ? "selected" : "" %>"><%= link_to t("videos") , admin_videos_path %></li>
    <%= tab :new_video , :route => :new_admin_video , :match_path => '/videos/new' , :css_class => 'last' %>
  </ul>
<% end %>

app/views/admin/videos/edit.html.erb
<h1><%=t("edit_video")%></h1>

<%= render 'shared/error_messages', :target => @video %>

<%= form_for(:video, :url => object_url, :html => { :method => :put }) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= render :partial => "admin/shared/edit_resource_links" %>
<% end %>

app/views/admin/videos/index.html.erb
<%= render :partial => 'sub_menu' %>
<h1><%= t("videos")%></h1>
<table class="index">
  <tr>
    <%= hook :admin_video_index_headers do %>
      <th><%= sort_link @search, :name, t("name") %></th>
      <th><%= t("youtube_url") %></th>
      <th><%= sort_link @search, :publish_up, t("publish_up") %></th>
      <th><%= sort_link @search, :publish_down, t("publish_down") %></th>
    <% end %>
    <th>
      <%= hook :admin_video_index_header_actions %>
    </th>
  </tr>
  <% @videos.each do |video| %>
    <tr id="<%= dom_id video %>">
      <%- locals = { :video => video } %>
      <%= hook :admin_video_index_rows, locals do %>
        <td width="15%"><%= video.name %></td>
        <td><iframe width="180" src="http://www.youtube.com/embed/<%= video.url %>" frameborder="0" allowfullscreen></iframe></td>
      	<td><%= video.publish_up.to_date %></td>
      	<td><%= video.publish_down.to_date if video.publish_down %></td>
      <% end %>
      <td class="actions" style="white-space:nowrap;">
        <%= hook :admin_video_index_row_actions, locals do %>
          <%= link_to_edit video %>
          &nbsp;
          <%= link_to_delete video %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/videos/new.html.erb
<%= render :partial => 'sub_menu' %>

<h1><%=t("new_video")%></h1>

<%= render 'shared/error_messages', :target => @video %>

<%= form_for(:video, :url => admin_videos_url) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= render :partial => "admin/shared/new_resource_links" %>
<% end %>